# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DbHadoop(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, hdfs_port: str='false', hdfs_url: str='true'):  # noqa: E501
        """DbHadoop - a model defined in Swagger

        :param hdfs_port: The hdfs_port of this DbHadoop.  # noqa: E501
        :type hdfs_port: str
        :param hdfs_url: The hdfs_url of this DbHadoop.  # noqa: E501
        :type hdfs_url: str
        """
        self.swagger_types = {
            'hdfs_port': str,
            'hdfs_url': str
        }

        self.attribute_map = {
            'hdfs_port': 'hdfs_port',
            'hdfs_url': 'hdfs_url'
        }

        self._hdfs_port = hdfs_port
        self._hdfs_url = hdfs_url

    @classmethod
    def from_dict(cls, dikt) -> 'DbHadoop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The db_hadoop of this DbHadoop.  # noqa: E501
        :rtype: DbHadoop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hdfs_port(self) -> str:
        """Gets the hdfs_port of this DbHadoop.

        hdfs http port  # noqa: E501

        :return: The hdfs_port of this DbHadoop.
        :rtype: str
        """
        return self._hdfs_port

    @hdfs_port.setter
    def hdfs_port(self, hdfs_port: str):
        """Sets the hdfs_port of this DbHadoop.

        hdfs http port  # noqa: E501

        :param hdfs_port: The hdfs_port of this DbHadoop.
        :type hdfs_port: str
        """
        if hdfs_port is None:
            raise ValueError("Invalid value for `hdfs_port`, must not be `None`")  # noqa: E501

        self._hdfs_port = hdfs_port

    @property
    def hdfs_url(self) -> str:
        """Gets the hdfs_url of this DbHadoop.

        hdfs http link  # noqa: E501

        :return: The hdfs_url of this DbHadoop.
        :rtype: str
        """
        return self._hdfs_url

    @hdfs_url.setter
    def hdfs_url(self, hdfs_url: str):
        """Sets the hdfs_url of this DbHadoop.

        hdfs http link  # noqa: E501

        :param hdfs_url: The hdfs_url of this DbHadoop.
        :type hdfs_url: str
        """
        if hdfs_url is None:
            raise ValueError("Invalid value for `hdfs_url`, must not be `None`")  # noqa: E501

        self._hdfs_url = hdfs_url
