# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DbModel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, hdfs: object=None, alerts: object=None, data: object=None):  # noqa: E501
        """DbModel - a model defined in Swagger

        :param hdfs: The hdfs of this DbModel.  # noqa: E501
        :type hdfs: object
        :param alerts: The alerts of this DbModel.  # noqa: E501
        :type alerts: object
        :param data: The data of this DbModel.  # noqa: E501
        :type data: object
        """
        self.swagger_types = {
            'hdfs': object,
            'alerts': object,
            'data': object
        }

        self.attribute_map = {
            'hdfs': 'hdfs',
            'alerts': 'alerts',
            'data': 'data'
        }

        self._hdfs = hdfs
        self._alerts = alerts
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'DbModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The db_model of this DbModel.  # noqa: E501
        :rtype: DbModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hdfs(self) -> object:
        """Gets the hdfs of this DbModel.

        required informations to get data from hdfs  # noqa: E501

        :return: The hdfs of this DbModel.
        :rtype: object
        """
        return self._hdfs

    @hdfs.setter
    def hdfs(self, hdfs: object):
        """Sets the hdfs of this DbModel.

        required informations to get data from hdfs  # noqa: E501

        :param hdfs: The hdfs of this DbModel.
        :type hdfs: object
        """

        self._hdfs = hdfs

    @property
    def alerts(self) -> object:
        """Gets the alerts of this DbModel.

        required informations to send alerts to flume  # noqa: E501

        :return: The alerts of this DbModel.
        :rtype: object
        """
        return self._alerts

    @alerts.setter
    def alerts(self, alerts: object):
        """Sets the alerts of this DbModel.

        required informations to send alerts to flume  # noqa: E501

        :param alerts: The alerts of this DbModel.
        :type alerts: object
        """

        self._alerts = alerts

    @property
    def data(self) -> object:
        """Gets the data of this DbModel.

        required informations to send data to flume  # noqa: E501

        :return: The data of this DbModel.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this DbModel.

        required informations to send data to flume  # noqa: E501

        :param data: The data of this DbModel.
        :type data: object
        """

        self._data = data
