# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UpdateModelVnf(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, access_host: object=None, metrics: object=None, agent_contrainte: object=None):  # noqa: E501
        """UpdateModelVnf - a model defined in Swagger

        :param access_host: The access_host of this UpdateModelVnf.  # noqa: E501
        :type access_host: object
        :param metrics: The metrics of this UpdateModelVnf.  # noqa: E501
        :type metrics: object
        :param agent_contrainte: The agent_contrainte of this UpdateModelVnf.  # noqa: E501
        :type agent_contrainte: object
        """
        self.swagger_types = {
            'access_host': object,
            'metrics': object,
            'agent_contrainte': object
        }

        self.attribute_map = {
            'access_host': 'access_host',
            'metrics': 'metrics',
            'agent_contrainte': 'agent contrainte'
        }

        self._access_host = access_host
        self._metrics = metrics
        self._agent_contrainte = agent_contrainte

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateModelVnf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The update_model_vnf of this UpdateModelVnf.  # noqa: E501
        :rtype: UpdateModelVnf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_host(self) -> object:
        """Gets the access_host of this UpdateModelVnf.

        required informations to access  host   # noqa: E501

        :return: The access_host of this UpdateModelVnf.
        :rtype: object
        """
        return self._access_host

    @access_host.setter
    def access_host(self, access_host: object):
        """Sets the access_host of this UpdateModelVnf.

        required informations to access  host   # noqa: E501

        :param access_host: The access_host of this UpdateModelVnf.
        :type access_host: object
        """

        self._access_host = access_host

    @property
    def metrics(self) -> object:
        """Gets the metrics of this UpdateModelVnf.

        required metrics to custom agent   # noqa: E501

        :return: The metrics of this UpdateModelVnf.
        :rtype: object
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics: object):
        """Sets the metrics of this UpdateModelVnf.

        required metrics to custom agent   # noqa: E501

        :param metrics: The metrics of this UpdateModelVnf.
        :type metrics: object
        """

        self._metrics = metrics

    @property
    def agent_contrainte(self) -> object:
        """Gets the agent_contrainte of this UpdateModelVnf.

        required metrics to custom agent   # noqa: E501

        :return: The agent_contrainte of this UpdateModelVnf.
        :rtype: object
        """
        return self._agent_contrainte

    @agent_contrainte.setter
    def agent_contrainte(self, agent_contrainte: object):
        """Sets the agent_contrainte of this UpdateModelVnf.

        required metrics to custom agent   # noqa: E501

        :param agent_contrainte: The agent_contrainte of this UpdateModelVnf.
        :type agent_contrainte: object
        """

        self._agent_contrainte = agent_contrainte
